=== electronicfieldguide/efg2/templateConfigFiles/TaxonPageTemplate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by UMASS Boston CSLabs (UMASS Boston CSLabs) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="characterValueType">
		<xs:complexContent>
			<xs:extension base="rankLabelTextType">
				<xs:attribute name="value" type="xs:string">
					<xs:annotation>
						<xs:documentation>The name of the field/character of the taxon being described..For example 'FlowerColor'. </xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="groupType" mixed="true">
		<xs:complexContent mixed="true">
			<xs:extension base="rankLabelTextType">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="characterValue">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="characterValueType"/>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="groups" type="groupsType">
						<xs:annotation>
							<xs:documentation>Encapsulates the various groups making up a template chosen by an author. Each group id must be unique within the scope of the groups element. Each group id is resolvable by the xpath leading to that group. group's  could have the same id as long as they do not vbelong to the same parent directly.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:choice>
				<xs:attribute name="id" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>All groups with the same ID are handled the same way by an XSLT template</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="taxonPageTemplateType">
		<xs:sequence>
			<xs:element name="groups" type="groupsType">
				<xs:annotation>
					<xs:documentation>Encapsulates the various groups making up a template chosen by an author. Each group id must be unique within the scope of the groups element. Each group id is resolvable by the xpath leading to that group. group's  could have the same id as long as they do not vbelong to the same parent directly.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="xslFileName" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The xsl file that will be used together with xml sources generated from this template to transform xml data of the given datasource to a taxon page</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="datasourceName" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the datasource whose data will be transformed using a given XSL File and the configured data for the datasource. This name must be unique within thescope of a TaxonPageTemplate element. see unique constraint on root element.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="displayName">
			<xs:annotation>
				<xs:documentation>Human readable name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="taxonPageTemplatesType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="TaxonPageTemplate" type="taxonPageTemplateType">
				<xs:annotation>
					<xs:documentation>Encapsulates information needed to transform a document to a chosen template by author.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="TaxonPageTemplates" type="taxonPageTemplatesType">
		<xs:annotation>
			<xs:documentation>The root of all datasources configured to use templates in the EFG or perhaps elsewhere</xs:documentation>
		</xs:annotation>
		<xs:unique name="datasourcename_unique">
			<xs:selector xpath="TaxonPageTemplate">
				<xs:annotation>
					<xs:documentation>Each taxonPageTemplate must have a unique datasource name.ie A datasource cannot be associated to more than one template</xs:documentation>
				</xs:annotation>
			</xs:selector>
			<xs:field xpath="@datasourceName">
				<xs:annotation>
					<xs:documentation>The field that must be unique throughout the document.</xs:documentation>
				</xs:annotation>
			</xs:field>
		</xs:unique>
	</xs:element>
	<xs:complexType name="rankLabelTextType">
		<xs:attribute name="rank" type="xs:int" use="required">
			<xs:annotation>
				<xs:documentation>Determines the order in which fields/characters are arranged within a container (group or characterValue Type)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string">
			<xs:annotation>
				<xs:documentation>A label for the whole group/character.Could be used to tag a set of characters for example on an html page..A label to be used instead of the field or character name..For instance an author could chose to display 'FlowerColor' as "Flower Color"(note the space between the two words)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="text" type="xs:string">
			<xs:annotation>
				<xs:documentation>A piece of text that could be displayed instead of the value of the character(states) from the datasource. </xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="groupsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="group" type="groupType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== electronicfieldguide/efg2/templateConfigFiles/marsahbogTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<TaxonPageTemplates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TaxonPageTemplate.xsd">
	<TaxonPageTemplate xslFileName="marshabogs.xsl" datasourceName="marshaBogsData">
		<groups>
			<group rank="1" id="1">
				<characterValue rank="1" text="Field Guide to the Bogs of Southern New England"/>
				<characterValue rank="2" text="by Marsha Salett"/>
			</group>
			<group rank="2" id="2" label="Taxonomy"/>
			<group rank="1" id="3">
				<characterValue rank="1" value="Common Name"/>
				<characterValue rank="2"/>
				<characterValue rank="3"/>
				<characterValue rank="4" value="Genus"/>
				<characterValue rank="5" value="Species"/>
				<characterValue rank="6" value="Author"/>
				<characterValue rank="7" value="Family"/>
				<characterValue rank="8" value="Family Common Name"/>
			</group>
			<group rank="2" id="4">
				<characterValue rank="1" value="Main Image"/>
			</group>
			<group rank="3" id="5">
				<characterValue rank="1" label="Synonyms" value="Common Name Synonyms"/>
			</group>
			<group rank="4" id="5">
				<characterValue rank="1" label="Description" value="Description"/>
				<characterValue rank="2" value="Description Images"/>
			</group>
			<group rank="5" id="5">
				<characterValue rank="1" label="Wetland indicator status" value="Wetland indicator status"/>
			</group>
			<group rank="6" id="5">
				<characterValue rank="1" label="Leaves" value="Leaves"/>
				<characterValue rank="2" value="Leaves Images"/>
			</group>
			<group rank="7" id="5">
				<characterValue rank="1" value="Flowers" label="Flowers"/>
				<characterValue rank="2" value="Flowers Images"/>
			</group>
			<group rank="8" id="5">
				<characterValue rank="1" value="Flowering Period" label="Flowering Period"/>
			</group>
			<group rank="9" id="5">
				<characterValue rank="1" value="Fruit" label="Fruit"/>
				<characterValue rank="2" value="Fruit Images"/>
			</group>
			<group rank="10" id="5">
				<characterValue rank="1" value="Fruiting Period" label="Fruiting Period"/>
			</group>
			<group rank="11" id="5">
				<characterValue rank="1" value="Habitat" label="Habitat"/>
			</group>
			<group rank="12" id="5">
				<characterValue rank="1" value="Range" label="Range"/>
			</group>
			<group rank="13" id="5">
				<characterValue rank="1" value="Associates" label="Associates"/>
			</group>
			<group rank="14" id="5">
				<characterValue rank="1" value="Similar Species" label="Similar Species"/>
				<characterValue rank="2" value="Similar Species Images" label="Similar Species Captions"/>
			</group>
			<group rank="15" id="5">
				<characterValue rank="1" value="Seasonal Diagnostics" label="Seasonal Diagnostics"/>
				<characterValue rank="2" value="Seasonal Diagnostics Images"/>
			</group>
			<group rank="16" id="6">
				<characterValue rank="1" text="(c) 1998-2006 Marsha Salett"/>
			</group>
		</groups>
	</TaxonPageTemplate>
</TaxonPageTemplates>

=== electronicfieldguide/efg2/templateConfigFiles/BillsTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<TaxonPageTemplates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TaxonPageTemplate.xsd">
	<TaxonPageTemplate xslFileName="billFamilyTaxonPage.xsl" datasourceName="ithData">
		<groups>
			<!-- Header section -->
			<group rank="1" id="1">
				<characterValue rank="1" value="Genus"/>
				<characterValue rank="2" value="Species"/>
				<characterValue rank="3" value="Author"/>
			</group>
			<group rank="2" id="2">
				<characterValue rank="1" value="Family"/>
				<characterValue rank="2" value="Family common name"/>
			</group>
			<!-- Images section -->
			<group rank="3" id="3">
				<characterValue rank="1" label="Flower" value="Image fl lg"/>
				<characterValue rank="2" label="Fruit" value="Image fr lg"/>
				<characterValue rank="3" label="Fruit3" value="Flower"/>
				<characterValue rank="4" value="Flowering habit"/>
			</group>
			<!-- Identification section  -->
			<group rank="4" id="4">
				<characterValue rank="1" value="Identification"/>
			</group>
			<!-- Descriptions, Similar Species Section-->
			<group rank="5" id="5">
				<characterValue rank="1" value="Description"/>
				<characterValue rank="2" value="Local distribution"/>
				<characterValue rank="3" value="Habitat"/>
				<characterValue rank="4" value="Species range"/>
				<characterValue rank="5" value="Abundance"/>
				<characterValue rank="6" value="Phenology"/>
				<characterValue rank="7" value="Pollinators"/>
				<characterValue rank="8" value="Similar species"/>
				<characterValue rank="9" value="Comments"/>
				<characterValue rank="10" value="Herbivores"/>
			</group>
			<!-- Copyright -->
			<group rank="6" id="6" label="Credits">
				<characterValue rank="1" value="Credits"/>
			</group>
		</groups>
	</TaxonPageTemplate>
</TaxonPageTemplates>
