=== electronicfieldguide/efg2/schema/EFGDocument.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by UMASS Boston CSLabs (UMASS Boston CSLabs) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="EFGDocument">
		<xs:annotation>
			<xs:documentation>An EFGDocument element is the root node of all EFGDocuments. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TaxonEntry" type="TaxonEntryType" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>A container that holds data(characters and states for e.g)  for a taxon.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="submitterName" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>The name of the person(s) who authored the document</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="datasource" use="optional">
				<xs:annotation>
					<xs:documentation>The name of the datasource if the document comes from more than one datasource, then a comma separeted list of datasource names. If the datasource is unknown then leave as blank or the empty string</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="moreData"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="EFGListType" mixed="true">
		<xs:attribute name="caption" type="xs:string">
			<xs:annotation>
				<xs:documentation>An optional caption</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="EFGListsType">
		<xs:sequence>
			<xs:element name="EFGList" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>One member of the list</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="EFGListType">
							<xs:attribute name="serviceLink">
								<xs:annotation>
									<xs:documentation>Could be used by consuming applications to make links on the name of the current member of the lists.@@@ Should resolve to a local efg look up if not specified by author</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the list. For example similar species</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type">
			<xs:annotation>
				<xs:documentation>The type of the members of the list, (must be one of mediaresource, simple, or an efgList)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="efgList"/>
					<xs:enumeration value="mediaresource"/>
					<xs:enumeration value="simple"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ordered">
			<xs:annotation>
				<xs:documentation>Indicates whether the order in which the members are listed matters</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:boolean"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="serviceLink">
			<xs:annotation>
				<xs:documentation>A global text that could be used in queries.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ItemType" mixed="true">
		<xs:attribute name="caption">
			<xs:annotation>
				<xs:documentation>An optional caption to use for the character for display purposes for instance</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="A_true_northwoods_gem_moosewood_is_happiest_in_the_light_shade_of_larger_trees._Its_big_three-pointed_leaves_and_especially_its_sinuously_striped_green_white_and_silver_bark_make_it_instantly_recognizable."/>
					<xs:enumeration value="Acer"/>
					<xs:enumeration value="Acer_pensylvanicum"/>
					<xs:enumeration value="Acer_saccharum"/>
					<xs:enumeration value="April"/>
					<xs:enumeration value="April-May"/>
					<xs:enumeration value="Eastern_North_America"/>
					<xs:enumeration value="Garden_in_the_Woods"/>
					<xs:enumeration value="Garden_in_the_Woods,_Nasami_Farm"/>
					<xs:enumeration value="Moosewood"/>
					<xs:enumeration value="Sugar_Maple"/>
					<xs:enumeration value="The_tree_that_made_New_England_famous._Sugar_maple_is_certainly_one_of_the_glories_of_the_fall_landscape_and_the_trees_grow_reasonably_fast_when_young._Avoid_roadside_locations_as_road_salt_is_harmful."/>
					<xs:enumeration value="blue_and_green"/>
					<xs:enumeration value="green"/>
					<xs:enumeration value="part_sun,_shade"/>
					<xs:enumeration value="pensylvanicum"/>
					<xs:enumeration value="saccharum"/>
					<xs:enumeration value="sun,_shade"/>
					<xs:enumeration value="tree"/>
					<xs:enumeration value="yellow"/>
					<xs:enumeration value="yellow-green"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ItemsType">
		<xs:sequence>
			<xs:element name="Item" type="ItemType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>A state of the character</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:annotation>
				<xs:documentation>The name of the Character to be described</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Color of Flowers"/>
					<xs:enumeration value="Common Name"/>
					<xs:enumeration value="Flower Color"/>
					<xs:enumeration value="Genus"/>
					<xs:enumeration value="Geographic Range"/>
					<xs:enumeration value="Growth Form"/>
					<xs:enumeration value="Light"/>
					<xs:enumeration value="Months in Bloom"/>
					<xs:enumeration value="Plant Description"/>
					<xs:enumeration value="Range"/>
					<xs:enumeration value="Sale Location"/>
					<xs:enumeration value="Scientific Name"/>
					<xs:enumeration value="Species"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ordered">
			<xs:annotation>
				<xs:documentation>indicates whether the order of the states for this character matters</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:boolean"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MediaResourceType" mixed="true">
		<xs:attribute name="caption" type="xs:string">
			<xs:annotation>
				<xs:documentation>An optional caption to be used for display purposes</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="ResourceTypeEnum" default="Image">
			<xs:annotation>
				<xs:documentation>Must be one of VIDEO, AUDIO,IMAGE as defiend in resourcesType</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MediaResourcesType">
		<xs:annotation>
			<xs:documentation>A  type for the MediaResourcs element</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="MediaResource" type="MediaResourceType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>A mediaresource </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:annotation>
				<xs:documentation>The name of the field for the mediaresource for example 'flowers', 'buds', 'eggs'</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Seasons in Bloom"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ordered" default="false">
			<xs:annotation>
				<xs:documentation>Indicates whether all the mediaresources are ordered(true) or not. The default is false</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:boolean"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="StatisticalMeasureType">
		<xs:annotation>
			<xs:documentation>A StatisticalMeasure type.Indicates the min and max value of the Statistical measure</xs:documentation>
		</xs:annotation>
		<xs:attribute name="min" type="xs:double" use="required">
			<xs:annotation>
				<xs:documentation>The minimum value for this statistical measure</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="max" type="xs:double" use="required">
			<xs:annotation>
				<xs:documentation>The maximum value of this statistical measure</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="units" type="xs:string">
			<xs:annotation>
				<xs:documentation>The units if any for this statistical measure</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="StatisticalMeasuresType">
		<xs:sequence>
			<xs:element name="StatisticalMeasure" type="StatisticalMeasureType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>A statistical measure for the Statistical measures Character. </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:annotation>
				<xs:documentation>The StatisticalMeasure character</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Height"/>
					<xs:enumeration value="Plant Height"/>
					<xs:enumeration value="Zone"/>
					<xs:enumeration value="Zone2"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ordered" default="false">
			<xs:annotation>
				<xs:documentation>true if this measure's data is ordered.false otherwise. The default is false</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:boolean"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TaxonEntryType">
		<xs:annotation>
			<xs:documentation>Describes the properties of a taxon</xs:documentation>
		</xs:annotation>
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Items" type="ItemsType">
				<xs:annotation>
					<xs:documentation>Anything else that is not an EFGList, MediaResources or a StatisticalMeasure may fit into this container. This container contains one or more Item elements</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="StatisticalMeasures" type="StatisticalMeasuresType">
				<xs:annotation>
					<xs:documentation>Indicates the statistical measures for the current taxon.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="EFGLists" type="EFGListsType">
				<xs:annotation>
					<xs:documentation>Indicates a list of names/things For example similar species</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="MediaResources" type="MediaResourcesType">
				<xs:annotation>
					<xs:documentation>A container that encpasulates the mediaresources( audio,video,image names for e.g) for the current taxon</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="datasource" type="xs:string">
			<xs:annotation>
				<xs:documentation>Sometimes the EFGDocument is constructed from many different datasources. Having a datasource name here indicates where the data comes from. If data for this taxon comes form multiple datasources a comma separated list of datasource names could be used</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ResourceTypeEnum">
		<xs:annotation>
			<xs:documentation xml:lang="en-us">This enumeration is identical with the DCMI Type Vocabulary (http: //dublincore.org/documents/dcmi-terms/, as of 6/2004), except that an additional type "Other" has been added. Its purpose is to provide a framework of broad media or resource type terms, without the technical detail provided by the large number of MIME types. The annotations are largely based on those from the DublinCore metadata initiative vocabulary.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:NCName">
			<xs:enumeration value="Image">
				<xs:annotation>
					<xs:documentation xml:lang="en-us">Image -- An image is a primarily symbolic visual representation other than text. For example - images and photographs of physical objects, paintings, prints, drawings, other images and graphics, animations and moving pictures, film, diagrams, maps, musical notation. Note that image may include both electronic and physical representations.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Text">
				<xs:annotation>
					<xs:documentation xml:lang="en-us">Text -- A text is a resource whose content is primarily words for reading. For example - books, letters, dissertations, poems, newspapers, articles, archives of mailing lists. Note that facsimiles or images of texts are still of the genre text. Text may contain embedded still image illustrations, e. g., formatted html pages.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Audio"/>
			<xs:enumeration value="Video"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== electronicfieldguide/efg2/schema/sampleEFGDoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<EFGDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EFGDocument.xsd">
	<datasources>
		<datasource submitterRef="1" name="IthData" efgKey="1"/>
	</datasources>
	<TaxonEntries>
		<TaxonEntry>
			<Items ordered="false" name="Migration">
				<Item resourceLink="http://alpaca.cs.umb.edu/efg/search?" efgKeyRef="1"  annotation="Migration is Common" caption="Migration pattern">Common</Item>
			</Items>
			<Items ordered="false" name="Scientific name">
				<Item resourceLink="http://alpaca.cs.umb.edu/efg/search?Scientific name=" efgKeyRef="1"  annotation="xx" caption="xxx">Pteronymia notilla</Item>
			</Items>
			<Items ordered="false" name="Identification">
				<Item resourceLink="http://alpaca.cs.umb.edu/efg/search?Scientific name=" efgKeyRef="1"  annotation="xx" caption="xxx">Antennae black, forewing costa all black, ventral forewing border with white spot line, markings blacker than fulvimargo.
</Item>
			</Items>
			<EFGLists name="Larval food plants" ordered="false" resourceLink="">
				<EFGList efgKeyRef="1" annotation="ccc" caption="ccc" resourceLink="Scientific Name">Solanum tuerckheimii</EFGList>
			</EFGLists>
			<MediaResources name="Image: female ventral" ordered="false">
				<MediaResource efgKeyRef="1" annotation="An image of the female ventral of  Ithomia notilla" caption="Female ventral" resourceLink="http://efg.cs.umb.edu/xxx.jpg" type="Image">Pte-not-fv-620-184.jpg#Pte-not-fv-620.jpg</MediaResource>
			</MediaResources>
			<MediaResources name="Image: female dorsal" ordered="false">
				<MediaResource efgKeyRef="1" annotation="An image of the female dorsal of  Ithomia notilla" caption="Image" resourceLink="http://efg.cs.umb.edu/xxx.jpg" type="Image">Pte-not-fd-620-184.jpg#Pte-not-fd-620.jpg</MediaResource>
			</MediaResources>
			<StatisticalMeasures name="Pacific slope">
				<StatisticalMeasure efgKeyRef="1" min="1200" max="1500" units="m"/>
			</StatisticalMeasures>
		</TaxonEntry>
	</TaxonEntries>
	<submitters>
		<submitter name="Bill Haber" submitterKey="1"/>
	</submitters>
</EFGDocument>
